#!/bin/bash

# Usage: PG_HOST='database.myhost.com' PG_DATABASE='mydatabase' PG_USER='myuser' ./import_postal_codes

GEONAMES_URL='http://download.geonames.org/export/zip/allCountries.zip'

if [ ! -f 'allCountries.zip' ]; then
    wget "$GEONAMES_URL" || exit 1
fi

psql --host="$PG_HOST" --dbname="$PG_DATABASE" --username="$PG_USER" --file='create_table.sql' || exit 1
echo 'Copy data from text file to database.'
psql --host="$PG_HOST" --dbname="$PG_DATABASE" --username="$PG_USER" --file='copy_table.sql' || exit 1
